### ISSUE TITLE
Sending `tts-progress` with no listeners registered

### ISSUE THREAD

**Issue by IjzerenHein** [ak1394/react-native-tts#1]
Hi, first of all, awesomeness that you wrote this library 😃 😃 😃

I've just started using it and came across the following warnings. When I call `tts.speak` it shows the following warnings:

![image](https://cloud.githubusercontent.com/assets/6184593/19596639/df06510a-978f-11e6-9ef0-d276c2a76dea.png)

I don't have any listeners registered.

cheers,
Hein

**Comment by ak1394** [comment]
Hi Hein, you are very welcome! These warnings are harmless, and will not be displayed in the production build. If you want to disable them during development, have a look at:

https://facebook.github.io/react-native/docs/debugging.html#warnings
the part about console.ignoredYellowBox

Regards,
Anton

**Comment by ak1394** [comment]
I agree, the problem is that I don't know a good way to solve it - the warnings are coming from React Native Event Emitter module:

```objective-c
  if (_listenerCount > 0) {
    [_bridge enqueueJSCall:@"RCTDeviceEventEmitter"
                    method:@"emit"
                      args:body ? @[eventName, body] : @[eventName]
                completion:NULL];
  } else {
    RCTLogWarn(@"Sending `%@` with no listeners registered.", eventName);
  }
```

So to handle it, I would either have to make module aware of how many listeners there are, or to install some dummy listeners on library init, and I dislike both of these solutions.

However, I don't see these warnings in the yellow boxes myself, in my case these would only show in the trace, which is barely noticeable. What version of React Native are you using?

I'm happy you find the library useful, however it's just a tiny wrapper on top of the respective platform APIs, so for downloading language packs you have to thank good folks at Google ;)

**Comment by uc-asa** [comment]
I agree with  @IjzerenHein and it works for me
